language: java

os: linux

dist: xenial

jdk: openjdk11

services:
  - xvfb

sudo: false
install: true

addons:
  sonarcloud:
    organization: "document-archiver"

before_script:
  - pwd
  - ls -la
  - cp src/daSettings/settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean jacoco:prepare-agent test jacoco:report sonar:sonar
  - mvn package -P linux-environment -DskipTests
  - mvn package -P mac-environment -DskipTests
  - mvn package -P win-environment -DskipTests
  - mvn org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy-file -Durl=https://repository.sophisticatedapps.com/releases -DrepositoryId=repository-sophisticatedapps -Dfile=target/document-archiver-1.1.0-SNAPSHOT.jar -DpomFile=pom.xml -Dfiles=target/document-archiver-1.1.0-SNAPSHOT-linux.jar,target/document-archiver-1.1.0-SNAPSHOT-mac.jar,target/document-archiver-1.1.0-SNAPSHOT-win.jar -Dclassifiers=linux,mac,win -Dtypes=jar,jar,jar
  - DA_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - echo $DA_VERSION
