language: java

os: linux

dist: xenial

jdk: openjdk11

services:
  - xvfb

sudo: false
install: true

addons:
  sonarcloud:
    organization: "document-archiver"

script:
  - mvn clean verify sonar:sonar
