language: java

os: linux

dist: xenial

jdk: openjdk11

services:
  - xvfb

sudo: false
install: true

addons:
  sonarcloud:
    organization: "document-archiver"

before_script:
  - cp /src/deployment/settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean jacoco:prepare-agent test jacoco:report sonar:sonar
  - mvn deploy -P linux-environment -DskipTests
  - mvn deploy -P mac-environment -DskipTests
  - mvn deploy -P win-environment -DskipTests
